  /**
   *  Returns an observable sequence that terminates with an exception, using the specified scheduler to send out the single onError message.
   *  There is an alias to this method called 'throwError' for browsers <IE9.
   * @param ***REMOVED***Mixed***REMOVED*** error An object used for the sequence's termination.
   * @param ***REMOVED***Scheduler***REMOVED*** scheduler Scheduler to send the exceptional termination call on. If not specified, defaults to Scheduler.immediate.
   * @returns ***REMOVED***Observable***REMOVED*** The observable sequence that terminates exceptionally with the specified exception object.
   */
  var observableThrow = Observable['throw'] = Observable.throwError = function (error, scheduler) ***REMOVED***
    isScheduler(scheduler) || (scheduler = immediateScheduler);
    return new AnonymousObservable(function (observer) ***REMOVED***
      return scheduler.schedule(function () ***REMOVED***
        observer.onError(error);
      ***REMOVED***);
    ***REMOVED***);
  ***REMOVED***;

  /** @deprecated use #some instead */
  Observable.throwException = function () ***REMOVED***
    //deprecate('throwException', 'throwError');
    return Observable.throwError.apply(null, arguments);
  ***REMOVED***;
